default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: prepared_statements_dev

test:
  <<: *default
  database: prepared_statements_test

production:
  <<: *default
  database: prepared_statements
